package com.example.apirateslifeforme.data.database.pirateSaved

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.*

@Entity(tableName = "pirate_table")
data class PirateMember(
    @PrimaryKey(autoGenerate = true) val pirate_id: Int = 0, //should this be autogenerated?
    val pirateName: String,
    val position: String,
    val dateJoined: Date,
    val pirateNum: Int
)